### ISSUE TITLE
the "chef_license" entry in CHEF_RB_TPL_PATH_KEYS causes failure

### ISSUE THREAD

**Issue by mromero-convoso** [number5/cloud-init#16]
https://github.com/number5/cloud-init/blob/a64b73808857fa7b4f262422ce2c87eedbce10d5/cloudinit/config/cc_chef.py#L73

Hello - I noticed while getting cloud-init to bootstrap Chef that the "chef_license" entry caused Cloud-init to fail:
'''
2021-02-23 18:36:24,030 - util.py[DEBUG]: Running module chef (<module 'cloudinit.config.cc_chef' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_chef.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 848, in _run_modules
    ran, _r = cc.run(run_name, mod.handle, func_args,
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 185, in run
    results = functor(*args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_chef.py", line 445, in handle
    util.ensure_dirs(param_paths)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1504, in ensure_dirs
    ensure_dir(d, mode)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1557, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
'''

Please let me know if you have any issues replicating.

**Comment by Alberts00** [comment]
I think this is a mirror repository. AFAIK the correct place to report issues for cloud-init is on [Launchpad](https://bugs.launchpad.net/cloud-init).
There is already an ongoing issues related to chef_license - [#1912424](https://bugs.launchpad.net/cloud-init/+bug/1912424) "Chef module fails to complete when chef_license is specified".

**Comment by powersj** [comment]
fwiw, while bugs are still tracked on Launchpad, development of cloud-init has moved to GitHub here: https://github.com/canonical/cloud-init
